# Generated by Django 2.1 on 2022-01-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Acadmics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maths', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Biology', models.IntegerField()),
                ('English', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('Roll_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Class', models.CharField(max_length=100)),
                ('School', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=10)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student_acadmics',
            name='Roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student_Info'),
        ),
    ]
